<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YMM.Data\YMM.Data.csproj" />
    <ProjectReference Include="..\YMM.Infrastructure\YMM.Infrastructure.csproj" />
    <ProjectReference Include="..\YMM.Service\YMM.Service.csproj" />
  </ItemGroup>

</Project>
